apiVersion: arubacloud.ogen.krateo.io/v1-0-0
kind: DatabaseBackup
metadata:
  name: example-databasebackup
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: databasebackup-config
    namespace: default
  projectId: REPLACE
  metadata:
    name: example-databasebackup
    location: {}
    tags: []
  properties:
    # fill from openapi/database.json
