apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: Grant
metadata:
  name: example-grant
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: grant-config
    namespace: default
  projectId: REPLACE
  dbaasId: REPLACE
  databaseName: REPLACE
  user: {}
  role: {}
