apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: ElasticIp
metadata:
  name: example-elasticip
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: elasticip-config
    namespace: default
  projectId: REPLACE
  metadata:
    name: example-elasticip
    location: {}
    tags: []
  properties:
    # fill from openapi/network.json
