apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: CloudServerConfiguration
metadata:
  name: cloudserver-config
  namespace: default
spec:
  authentication:
    bearer:
      tokenRef:
        name: arubacloud-token
        namespace: default
        key: token
  configuration:
    query:
      findby:
        api-version: '1.0'
      get:
        api-version: '1.0'
