apiVersion: arubacloud.ogen.krateo.io/v1-0-0
kind: KeyPair
metadata:
  name: example-keypair
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: keypair-config
    namespace: default
  projectId: REPLACE
  metadata:
    name: example-keypair
    location: {}
    tags: []
  properties:
    # fill from openapi/compute.json
