# Aruba Cloud AlertRule (metering provider) - generated, no proxy.
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: arubacloud-metering-alertrule
spec:
  oasPath: configmap://krateo-system/arubacloud-metering-openapi/metering.json
  resourceGroup: arubacloud.ogen.krateo.io
  resource:
    kind: AlertRule
    identifiers:
    - name
    additionalStatusFields:
    - id
    excludedSpecFields:
    - alertRulesId
    verbsDescription:
    - action: findby
      method: GET
      path: /projects/{projectId}/providers/Aruba.Insight/alertRules
    - action: get
      method: GET
      path: /projects/{projectId}/providers/Aruba.Insight/alertRules/{alertRulesId}
      requestFieldMapping:
      - inPath: alertRulesId
        inCustomResource: status.id
    - action: create
      method: POST
      path: /projects/{projectId}/providers/Aruba.Insight/alertRules
    - action: update
      method: PUT
      path: /projects/{projectId}/providers/Aruba.Insight/alertRules/{alertRulesId}
      requestFieldMapping:
      - inPath: alertRulesId
        inCustomResource: status.id
    - action: delete
      method: DELETE
      path: /projects/{projectId}/providers/Aruba.Insight/alertRules/{alertRulesId}
      requestFieldMapping:
      - inPath: alertRulesId
        inCustomResource: status.id
    configurationFields:
    - fromOpenAPI:
        name: api-version
        in: query
      fromRestDefinition:
        actions:
        - '*'
    - fromOpenAPI:
        name: filter
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: sort
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: projection
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: offset
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: limit
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: serviceTypology
        in: query
      fromRestDefinition:
        actions:
        - findby
    - fromOpenAPI:
        name: serviceName
        in: query
      fromRestDefinition:
        actions:
        - findby
