apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: Kmip
metadata:
  name: example-kmip
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: kmip-config
    namespace: default
  projectId: REPLACE
  id: REPLACE
  name: REPLACE
