apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: KmsConfiguration
metadata:
  name: kms-config
  namespace: default
spec:
  authentication:
    apiKey:
      tokenRef:
        name: arubacloud-token
        namespace: default
        key: token
      header: Authorization
      valuePrefix: 'Bearer '
  configuration:
    query:
      findby:
        api-version: '1.0'
      get:
        api-version: '1.0'
      create:
        api-version: '1.0'
      update:
        api-version: '1.0'
      delete:
        api-version: '1.0'
