apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: Snapshot
metadata:
  name: example-snapshot
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: snapshot-config
    namespace: default
  projectId: REPLACE
  metadata:
    name: example-snapshot
    location: {}
    tags: []
  properties:
    # fill from openapi/storage.json
