apiVersion: arubacloud.ogen.krateo.io/v1alpha1
kind: BackupPolicy
metadata:
  name: example-backuppolicy
  namespace: default
  annotations:
    krateo.io/connector-verbose: 'true'
spec:
  configurationRef:
    name: backuppolicy-config
    namespace: default
  projectId: REPLACE
  metadata:
    name: example-backuppolicy
    tags: []
  properties:
    # fill from openapi/schedule.json
